default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: challenge
  password: challenge
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: challenge

test:
  <<: *default
  database: challenge_test

production:
  <<: *default
  database: challenge_prod
